# Generated by Django 3.0.5 on 2021-04-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('surname', models.CharField(db_index=True, max_length=100)),
                ('degree', models.CharField(db_index=True, default='Student', max_length=10)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=80, null=True)),
                ('institution', models.CharField(db_index=True, max_length=255, verbose_name='Институција + Адреса')),
                ('image', models.ImageField(blank=True, db_index=True, null=True, upload_to='img/')),
            ],
            options={
                'ordering': ['institution'],
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='First and last name')),
                ('email', models.EmailField(max_length=70, verbose_name='Your e-mail')),
                ('description', models.TextField(verbose_name='Describe the issue in detail')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True)),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='volumes/pdfs/%Y')),
                ('first_page', models.CharField(db_index=True, max_length=10)),
                ('last_page', models.CharField(db_index=True, max_length=10)),
                ('date', models.IntegerField(db_index=True, verbose_name='Година на издавање')),
                ('full_date', models.DateField(verbose_name='Целосен датум на издавање')),
                ('issue', models.ManyToManyField(to='journal.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField(db_index=True)),
                ('image', models.ImageField(db_index=True, upload_to='post_images')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tag', models.ManyToManyField(to='journal.PostTag')),
            ],
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_title', models.CharField(db_index=True, max_length=255, verbose_name='Наслов на трудот')),
                ('title', models.TextField(db_index=True, verbose_name='Декориран наслов')),
                ('citation_date', models.DateField(db_index=True, verbose_name='Датум на публикување')),
                ('citation_firstpage', models.CharField(db_index=True, max_length=10, verbose_name='Број на првата страница')),
                ('citation_lastpage', models.CharField(db_index=True, max_length=10, verbose_name='Број на последната страница')),
                ('reference_author', models.EmailField(db_index=True, max_length=60, verbose_name='E-mail на првиот автор')),
                ('abstract', models.TextField(db_index=True, verbose_name='Извод')),
                ('keywords', models.CharField(db_index=True, max_length=300, verbose_name='Клучни зборови')),
                ('document', models.FileField(db_index=True, upload_to='pdfs/', verbose_name='.pdf')),
                ('slug_field', models.SlugField(unique=True, verbose_name='Скратено')),
                ('authors', models.ManyToManyField(db_index=True, to='journal.Author', verbose_name='Автор/и')),
                ('citation_volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Volume', verbose_name='Том')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.Sections', verbose_name='Секција')),
            ],
            options={
                'ordering': ['citation_volume'],
            },
        ),
    ]
