# Generated by Django 3.0.5 on 2021-04-27 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='name',
            field=models.CharField(default='Name', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manuscript',
            name='citation_issn',
            field=models.CharField(default='default', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manuscript',
            name='citation_language',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manuscript',
            name='image',
            field=models.ImageField(blank=True, upload_to='manuscript_images/'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='udc',
            field=models.CharField(default='default', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volume',
            name='citation_issn',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volume',
            name='citation_journal_title',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volume',
            name='citation_language',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volume',
            name='udc',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='institution',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Institution and address'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='abstract',
            field=models.TextField(verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='authors',
            field=models.ManyToManyField(db_index=True, to='journal.Author', verbose_name='Author/s'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='citation_date',
            field=models.DateField(verbose_name='Publishing date'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='citation_firstpage',
            field=models.CharField(max_length=10, verbose_name='First page number'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='citation_lastpage',
            field=models.CharField(max_length=10, verbose_name='Last page number'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='citation_title',
            field=models.CharField(max_length=255, verbose_name='Manuscript title'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='citation_volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Volume', verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='keywords',
            field=models.CharField(max_length=300, verbose_name='Key words'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='reference_author',
            field=models.EmailField(max_length=60, verbose_name='Reference author'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.Sections', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='title',
            field=models.TextField(verbose_name='Decorated title'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='date',
            field=models.IntegerField(verbose_name='Publishing year'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='full_date',
            field=models.DateField(verbose_name='Full date'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=models.CharField(default='Your volume name', max_length=30),
        ),
    ]
